#makefile for compiling all the java

all: p1 duplicateException emptySymbolTableException symbol symbolTable

p1: 
	javac P1.java

duplicateException:
	javac DuplicateException.java

emptySymbolTableException:
	javac EmptySymbolTableException.java

symbol:
	javac Symbol.java

symbolTable:
	javac SymbolTable.java

clean:
	rm -f P1.class Symbol.class SymbolTable.class DuplicateException.class EmptySymbolTableException.class
