
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Jan 10 14:11:16 CST 2003
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 29;
  public static final int EQUALS = 33;
  public static final int GREATER = 36;
  public static final int LPAREN = 21;
  public static final int INT = 2;
  public static final int LESS = 35;
  public static final int MINUS = 27;
  public static final int WRITE = 40;
  public static final int RPAREN = 22;
  public static final int NOT = 30;
  public static final int SEMICOLON = 25;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int BOOL = 3;
  public static final int COMMA = 23;
  public static final int PLUS = 26;
  public static final int LESSEQ = 37;
  public static final int ASSIGN = 24;
  public static final int IF = 7;
  public static final int ID = 14;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int TRUE = 5;
  public static final int LCURLY = 17;
  public static final int LSQBRACKET = 19;
  public static final int CIN = 10;
  public static final int VOID = 4;
  public static final int RCURLY = 18;
  public static final int INTLITERAL = 15;
  public static final int TIMES = 28;
  public static final int ELSE = 8;
  public static final int COUT = 11;
  public static final int READ = 39;
  public static final int NOTEQUALS = 34;
  public static final int WHILE = 9;
  public static final int RSQBRACKET = 20;
  public static final int GREATEREQ = 38;
  public static final int STRINGLITERAL = 16;
  public static final int FALSE = 6;
}

