
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Apr 05 00:26:08 CDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 28;
  public static final int EQUALS = 32;
  public static final int GREATER = 35;
  public static final int LPAREN = 20;
  public static final int INT = 2;
  public static final int LESS = 34;
  public static final int MINUS = 26;
  public static final int WRITE = 39;
  public static final int RPAREN = 21;
  public static final int NOT = 29;
  public static final int SEMICOLON = 24;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int BOOL = 3;
  public static final int COMMA = 22;
  public static final int PLUS = 25;
  public static final int LESSEQ = 36;
  public static final int ASSIGN = 23;
  public static final int IF = 7;
  public static final int ID = 13;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int LCURLY = 16;
  public static final int LSQBRACKET = 18;
  public static final int CIN = 10;
  public static final int VOID = 4;
  public static final int RCURLY = 17;
  public static final int INTLITERAL = 14;
  public static final int TIMES = 27;
  public static final int ELSE = 8;
  public static final int COUT = 11;
  public static final int READ = 38;
  public static final int NOTEQUALS = 33;
  public static final int WHILE = 9;
  public static final int RSQBRACKET = 19;
  public static final int GREATEREQ = 37;
  public static final int STRINGLITERAL = 15;
  public static final int FALSE = 6;
}

